
version: 2.1
orbs:
  dotnet: ngs/dotnet@0.0.2
jobs: 
  build:
    docker:
      - image: shyam595/codingtest	
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dotnet
          command: sudo apt-get install -y dotnet-sdk-7.0
      - run:
          name: Restore packages
          command: dotnet restore

      - run:
          name: Build App
          command: dotnet build

      - run:
          name: Run App
          command: dotnet run
          