
version: 2
jobs: 
  build:
    docker:
      - image: shyam595/codingtest:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest 
