version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: shyam595/codingtest
    docker:
      - image: circleci/codingtest:dev
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master